[package]
name = "mandelrust"
version = "0.1.0"
edition = "2021"

[dependencies]
astro-float = "0.9.4"
image = "0.25.1"
itertools = "0.13.0"
nonempty = "0.10.0"
piston_window = "0.132.0"
rayon = "1.10.0"
